name: refi
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alsa-lib=1.2.3
  - anyio=3.1.0
  - argon2-cffi=20.1.0
  - async_generator=1.10
  - attrs=21.2.0
  - babel=2.9.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - bleach=3.3.0
  - brotli-python=1.0.9
  - brotlipy=0.7.0
  - ca-certificates=2020.12.5
  - certifi=2020.12.5
  - cffi=1.14.5
  - chardet=4.0.0
  - click=8.0.1
  - cryptography=3.4.7
  - dash=1.20.0
  - dash-core-components=1.16.0
  - dash-html-components=1.1.3
  - dash-renderer=1.9.1
  - dash-table=4.11.3
  - dataclasses=0.8
  - dbus=1.13.6
  - decorator=5.0.9
  - defusedxml=0.7.1
  - entrypoints=0.3
  - expat=2.3.0
  - flask=2.0.1
  - flask-compress=1.9.0
  - fontconfig=2.13.1
  - freetype=2.10.4
  - future=0.18.2
  - gettext=0.19.8.1
  - glib=2.68.2
  - glib-tools=2.68.2
  - gst-plugins-base=1.18.4
  - gstreamer=1.18.4
  - icu=68.1
  - idna=2.10
  - importlib-metadata=4.0.1
  - ipykernel=5.5.5
  - ipython=7.23.1
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.3
  - itsdangerous=2.0.1
  - jedi=0.18.0
  - jinja2=3.0.1
  - jpeg=9d
  - json5=0.9.5
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=6.1.12
  - jupyter_console=6.4.0
  - jupyter_core=4.7.1
  - jupyter_server=1.8.0
  - jupyterlab=3.0.15
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.5.2
  - jupyterlab_widgets=1.0.0
  - krb5=1.19.1
  - ld_impl_linux-64=2.35.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libclang=11.1.0
  - libedit=3.1.20191231
  - libevent=2.1.10
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgfortran-ng=9.3.0
  - libgfortran5=9.3.0
  - libglib=2.68.2
  - libgomp=9.3.0
  - libiconv=1.16
  - liblapack=3.9.0
  - libllvm11=11.1.0
  - libogg=1.3.4
  - libopenblas=0.3.15
  - libopus=1.3.1
  - libpng=1.6.37
  - libpq=13.3
  - libsodium=1.0.18
  - libstdcxx-ng=9.3.0
  - libuuid=2.32.1
  - libvorbis=1.3.7
  - libxcb=1.13
  - libxkbcommon=1.0.3
  - libxml2=2.9.12
  - lz4-c=1.9.3
  - markupsafe=2.0.1
  - matplotlib-inline=0.1.2
  - mistune=0.8.4
  - mysql-common=8.0.23
  - mysql-libs=8.0.23
  - nbclassic=0.2.8
  - nbclient=0.5.3
  - nbconvert=6.0.7
  - nbformat=5.1.3
  - ncurses=6.2
  - nest-asyncio=1.5.1
  - notebook=6.4.0
  - nspr=4.30
  - nss=3.65
  - numpy=1.20.3
  - openssl=1.1.1k
  - packaging=20.9
  - pandas=1.2.4
  - pandoc=2.13
  - pandocfilters=1.4.2
  - parso=0.8.2
  - pcre=8.44
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=21.1.2
  - plotly=4.14.3
  - prometheus_client=0.10.1
  - prompt-toolkit=3.0.18
  - prompt_toolkit=3.0.18
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pycparser=2.20
  - pygments=2.9.0
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyqt=5.12.3
  - pyqt-impl=5.12.3
  - pyqt5-sip=4.19.18
  - pyqtchart=5.12
  - pyqtwebengine=5.12.1
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - python=3.8.8
  - python-dateutil=2.8.1
  - python_abi=3.8
  - pytz=2021.1
  - pyyaml=5.4.1
  - pyzmq=22.0.3
  - qt=5.12.9
  - qtconsole=5.1.0
  - qtpy=1.9.0
  - readline=8.1
  - requests=2.25.1
  - retrying=1.3.3
  - send2trash=1.5.0
  - setuptools=49.6.0
  - six=1.16.0
  - sniffio=1.2.0
  - sqlite=3.35.5
  - terminado=0.10.0
  - testpath=0.5.0
  - tk=8.6.10
  - tornado=6.1
  - traitlets=5.0.5
  - urllib3=1.26.4
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.57.0
  - werkzeug=2.0.1
  - wheel=0.36.2
  - widgetsnbextension=3.5.1
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.5
  - yaml=0.2.5
  - zeromq=4.3.4
  - zipp=3.4.1
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - appdirs==1.4.4
    - black==21.6b0
    - cycler==0.10.0
    - dash-bootstrap-components==0.12.2
    - gunicorn==20.1.0
    - jupyter-autotime==1.1.0
    - jupyterthemes==0.20.0
    - kiwisolver==1.3.1
    - lesscpy==0.14.0
    - matplotlib==3.4.2
    - mypy-extensions==0.4.3
    - numpy-financial==1.0.0
    - pathspec==0.8.1
    - pillow==8.2.0
    - ply==3.11
    - python-dotenv==0.17.1
    - regex==2021.4.4
    - toml==0.10.2
prefix: /home/eric/anaconda3/envs/refi
